config/routes.rb
Rails.application.routes.draw do
  resources :notes
  authenticated :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticated :user do
    root 'static_pages#index', as: :authenticated_root
  end

  unauthenticated do
    root 'static_pages#welcome'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :feeds, except: :edit do
    member do
      delete 'unsubscribe', as: 'unsubscribe', to: 'feeds#unsubscribe'
    end
  end

  resources :posts, only: [] do
    member do
      post 'bookmark'
      delete 'bookmark', as: 'unbookmark', to: 'posts#unbookmark'
      post 'mark_read'
    end
  end

  get '/about' => "static_pages#about"
end

app/models/feed.rb
# == Schema Information
#
# Table name: feeds
#
#  id          :bigint           not null, primary key
#  favicon_url :string
#  title       :string           not null
#  url         :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_feeds_on_url  (url) UNIQUE
#

class Feed < ApplicationRecord
  validates :title, :url, presence: true
  validates :url, uniqueness: true

  has_many :posts

  # Creates a new feed from a feed url.
  #
  # @param url [String] the feed's url
  # @return [Feed] the created feed
  def self.create_from_url(url)
    feed = new(url: url)
    feed.parse_and_save
  end

  def parse_and_save
    begin
      parsed_feed = Feedjira.parse(HTTParty.get(url).body)
      self.favicon_url = build_favicon_url(url)
      self.title = parsed_feed.title
      save if changed?
      parse_and_save_posts(parsed_feed)
    rescue Feedjira::NoParserAvailable, Errno::ECONNREFUSED, SocketError
      errors.add(:url, 'invalid. Make sure you are entering the full URL ' \
                       "(starting with 'http'), and it links directly to the " \
                       'feed (not the normal website).')
    end
    self
  end

  private

  def parse_and_save_posts(parsed_feed)
    empty_feed = posts.none?
    parsed_feed.entries.each do |entry|
      post = Post.parse(entry)
      post.feed_id = id
      post.save! if empty_feed || post.new_post?
    end
  end

  def build_favicon_url(url)
    parsed_url = URI.parse(url)
    icon_url = "#{parsed_url.scheme}://#{parsed_url.host}/favicon.ico"
    return icon_url if
      HTTParty.head(icon_url).headers.content_type.starts_with?('image')
    return nil
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  layout 'reader/reader'
  before_action :authenticate_user!, :except => [:show]
  before_action :set_up_feed, :only => [:index, :show]

  def index
    @pagy, @posts = pagy(@posts)
  end

  def show
    @feed = Feed.find(params[:id])
    @pagy, @posts = pagy(@posts.where(feed_id: @feed.id))
  end

  def create
    url = FeedUrl.feed_url(params[:feed][:url])
    feed = Feed.find_by_url(url)
    if feed && !current_user.feeds.exists?(feed.id)
      current_user.feeds << feed
    elsif feed.nil?
      feed = Feed.create_from_url(url)
      current_user.feeds << feed if feed.persisted?
    end
    flash[:error] = feed.errors.full_messages if feed.errors.any?
    redirect_back(fallback_location: root_path)
  end

  def unsubscribe
    feed_id = params[:id]
    UserFeed.destroy_by(user_id: current_user.id, feed_id: feed_id)
    redirect_to feeds_path
  end

  private

  def set_up_feed
    @feeds = current_user.feeds
    @bookmarked_only = params[:bookmarked] == 'true'
    @bookmarked_posts = current_user.bookmarked_posts.load
    @posts = if params[:bookmarked]
               @bookmarked_posts
             elsif current_user.unread_only
               current_user.unread_posts
             else
               current_user.posts
             end
    @posts = @posts.includes(:feed, :user_posts).order(posted_at: post_order)
  end

  def post_order
    current_user.post_order
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/shared/_feed.html.erb
<div class="feed">
  <% posts.each do |post| %>
    <div class="post<%= post.read_by?(current_user) ? ' read' : ' unread' %><%= ' mark-unread' if current_user.unread_only && !@bookmarked_only %>" data-id="<%= post.id%>">
      <h3>
        <% if post.url %>
          <%= link_to post.title, post.url %>
        <% else %>
          <%= post.title %>
        <% end %>
      </h3>
      <div>
        <%= link_to post.feed.title, feed_path(post.feed) %>,
        <%= "#{post.author}, " if post.author.present? %>
        <%= post.posted_at.strftime('%Y-%m-%d') %>
      </div>
      <br>
      <div><%= post.content.html_safe if post.content %></div>
      <br>
      <div>
        <% if @bookmarked_posts.include?(post) %>
          <%= button_to 'Unbookmark',
              unbookmark_post_path(post), method: 'delete' %>
        <% else %>
          <%= button_to 'Bookmark', bookmark_post_path(post), method: 'post' %>
        <% end %>
      </div>
    </div>
    <hr>
  <% end %>
  <% if @pagy.count > Pagy::VARS[:items] %>
    <%== pagy_nav(@pagy) %>
  <% end %>
</div>

app/views/feeds/shared/_feeds_sidebar.html.erb
<div class="feed-sidebar">
  <div><strong>Subscribe</strong>:</div>
  <%= form_with model: Feed.new do |form| %>
    <%= form.label :url, 'Feed URL' %>
    <%= form.text_field :url %>
    <br>
    <%= form.submit 'Subscribe' %>
  <% end %>
  <br>
  <% if feeds.any? %>
    <div><strong>Feeds</strong>:</div>
    <% feeds.each do |feed| %>
      <%= link_to feed.title, feed %>
      <br>
    <% end %>
  <% end %>
  <br>
</div>