config/routes.rb
Rails.application.routes.draw do
  resources :notes
  authenticated :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  authenticated :user do
    root 'static_pages#index', as: :authenticated_root
  end

  unauthenticated do
    root 'static_pages#welcome'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :feeds, except: :edit do
    member do
      delete 'unsubscribe', as: 'unsubscribe', to: 'feeds#unsubscribe'
    end
  end

  resources :posts, only: [] do
    member do
      post 'bookmark'
      delete 'bookmark', as: 'unbookmark', to: 'posts#unbookmark'
      post 'mark_read'
    end
  end

  get '/about' => "static_pages#about"
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :bigint           not null, primary key
#  content    :text
#  private    :boolean
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Note < ApplicationRecord
  belongs_to :user

  DEFAULT_TITLE = 'unititled note'.freeze
  PLACEHOLDER_TEXT = 'Write your note here!'.freeze

  before_create do
    self.title = DEFAULT_TITLE if self.title.blank?
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  layout 'notes/notes'
  before_action :authenticate_user!, :except => [:show]

  def index
    @notes = current_user.notes
  end

  def new
    @note = Note.new(user_id: current_user.id, private: true)
  end

  def show
    @note = Note.find(params[:id])
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.content = CGI.escapeHTML(@note.content)
    if @note.save
      redirect_to @note
    else
      flash[:error] = @note.errors.full_messages
      render action: 'new'
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to @note
    else
      flash[:error] = @note.errors.full_messages
      render action: 'edit'
    end
  end

  private
  def note_params
    params.require(:note).permit(:title, :private, :content)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/notes/_header.html.erb
<header>
  <div class='logo'>
    <%= link_to root_path do %>
      <!-- <img src='/images/notes/logo.png'> -->
    <% end %>
  </div>
  <div class='header-links'>
    <% if current_user %>
      <%= link_to 'reader', feeds_path %> |
      <%= link_to 'notes', notes_path %> |
      <%= link_to 'about', about_path %> |
      <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'about', about_path %> |
      <%= link_to 'login', new_user_session_path %> |
      <%= link_to 'register', new_user_registration_path %>
    <% end %>
  </div>
  <hr>
</header>

app/views/layouts/notes/notes.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>The Simple Note</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple note editor."/>
    <link rel="shortcut icon" href="/images/notes_favicon.ico">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/notes/header' %>
    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <%= content_tag :div, class: "flash #{key}" do %>
          <% if value.is_a?(String) %>
            <%= content_tag :div, value %>
          <% else %>
            <% value.each do |subvalue| %>
              <%= content_tag :div, subvalue %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <hr>
    <% end %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>